import { createFileRoute } from "@tanstack/react-router"

export const Route = createFileRoute("/docs/fpf/publishing")({
  component: FpfPublishingPage,
})

function FpfPublishingPage() {
  return (
    <>
      <h1>Publishing a package</h1>
      <p>
        This guide walks through the full workflow for creating and publishing an FPF package to
        the registry — from scaffolding to a live install command.
      </p>

      <h2>Prerequisites</h2>
      <ul>
        <li>tsx CLI installed (<code>tsx --version</code>).</li>
        <li>An account on the registry with an API key (generate one in the dashboard under <em>API Keys</em>).</li>
      </ul>

      <h2>Step 1 — Scaffold the package</h2>
      <pre><code>{`mkdir my-pattern && cd my-pattern
tsx framework init`}</code></pre>
      <p>This creates <code>manifest.json</code>, <code>generators/</code>, and <code>templates/</code>.</p>

      <h2>Step 2 — Edit the manifest</h2>
      <p>Open <code>manifest.json</code> and fill in the required fields:</p>
      <pre><code>{`{
  "id": "my-pattern",
  "name": "My Pattern",
  "description": "A reusable pattern that adds X to TanStack Start projects.",
  "version": "1.0.0",
  "tsx_min": "0.4.0",
  "lang": "typescript",
  "provides": ["my-capability"],
  "generators": [
    {
      "id": "setup",
      "command": "generators/setup.rhai",
      "description": "Scaffold the integration.",
      "schema": {},
      "output_paths": ["src/lib/my-pattern.ts"]
    }
  ]
}`}</code></pre>

      <h2>Step 3 — Write generators and templates</h2>
      <p>
        Edit <code>generators/setup.rhai</code> to implement the scaffolding logic.
        Use <code>write_template("templates/my-file.ts.hbs", ctx)</code> to render a Handlebars
        template and write it to an output path.
      </p>
      <pre><code>{`// generators/setup.rhai
let ctx = #{
  project_name: input.project_name,
};
write_template("templates/my-pattern.ts.hbs", ctx);`}</code></pre>

      <p>Then edit <code>templates/my-pattern.ts.hbs</code>:</p>
      <pre><code>{`// Auto-generated by tsx install {{id}}
export const myPattern = "{{project_name}}"`}</code></pre>

      <h2>Step 4 — Validate</h2>
      <pre><code>tsx framework validate</code></pre>
      <p>Fix any reported errors before proceeding. Common issues:</p>
      <ul>
        <li>Missing required fields in <code>manifest.json</code>.</li>
        <li>Generator script path not found.</li>
        <li>Invalid semver in <code>version</code> or <code>tsx_min</code>.</li>
      </ul>

      <h2>Step 5 — Preview</h2>
      <p>Run the generator locally to confirm the output looks correct:</p>
      <pre><code>tsx framework preview --generator setup</code></pre>

      <h2>Step 6 — Publish</h2>
      <pre><code>{`tsx framework publish --api-key sk_live_YOUR_KEY_HERE`}</code></pre>
      <p>
        tsx will bundle the package into a <code>.tar.gz</code> archive and upload it to the registry.
        On success, the install command is printed:
      </p>
      <pre><code>tsx install my-pattern</code></pre>

      <h2>Publish to a self-hosted registry</h2>
      <pre><code>{`tsx framework publish \\
  --registry https://registry.my-org.com \\
  --api-key sk_live_...`}</code></pre>

      <h2>Bumping versions</h2>
      <p>
        Update the <code>version</code> field in <code>manifest.json</code> before each publish.
        The registry rejects duplicate version uploads. Follow semver:
      </p>
      <ul>
        <li><strong>Patch</strong> (<code>1.0.1</code>) — Bugfixes, no breaking changes.</li>
        <li><strong>Minor</strong> (<code>1.1.0</code>) — New generators or fields, backwards compatible.</li>
        <li><strong>Major</strong> (<code>2.0.0</code>) — Breaking changes to generators or manifest structure.</li>
      </ul>
    </>
  )
}
