import { createFileRoute } from "@tanstack/react-router"

export const Route = createFileRoute("/docs/fpf")({
  component: FpfPage,
})

function FpfPage() {
  return (
    <>
      <h1>Framework Package Format</h1>
      <p>
        The Framework Package Format (FPF) is the specification that all tsx packages follow.
        An FPF package is a versioned, self-describing bundle of code generators, templates, and
        metadata that can be installed into any compatible project with a single command.
      </p>

      <h2>What is a framework package?</h2>
      <p>
        Think of an FPF package as a smart scaffold. Unlike a plain code snippet or a library
        dependency, a framework package:
      </p>
      <ul>
        <li>Knows about your project structure and writes files into the right places.</li>
        <li>Declares capabilities it provides (e.g. <code>auth</code>, <code>crud</code>) so other packages can integrate with it.</li>
        <li>Integrates automatically with other installed packages via the <code>integrates_with</code> slot system.</li>
        <li>Is versioned and pinnable, so teams get reproducible scaffolding.</li>
      </ul>

      <h2>Directory layout</h2>
      <p>After installation, a package lives under <code>.tsx/packages/&lt;name&gt;/</code>:</p>
      <pre><code>{`.tsx/
└── packages/
    └── with-auth/
        ├── manifest.json       # Package manifest (pinned version)
        ├── generators/         # Rhai or shell generator scripts
        │   ├── setup.rhai      # Scaffolds the full auth integration
        │   └── add-route.rhai  # Adds a new protected route
        └── templates/          # Handlebars templates
            ├── auth.server.ts.hbs
            ├── auth.client.ts.hbs
            └── middleware.ts.hbs`}</code></pre>

      <h2>The manifest</h2>
      <p>
        Every package must have a <code>manifest.json</code> at its root. It declares the package
        identity, capabilities, generators, and integration slots. See{" "}
        <a href="/docs/fpf/manifest">stack.json reference</a> for the full field specification.
      </p>

      <h2>Generators</h2>
      <p>
        Generators are scripts that receive a JSON input schema and write files to the project.
        They are defined in the <code>generators[]</code> array of the manifest and invoked via:
      </p>
      <pre><code>tsx run &lt;package&gt;:&lt;generator&gt; [--input '{"key":"value"}']</code></pre>

      <h2>The slot system</h2>
      <p>
        The <code>integrates_with</code> map in the manifest describes how this package modifies
        other packages' output. For example, the <code>with-auth</code> package can inject a
        session check into routes generated by <code>tanstack-crud</code>:
      </p>
      <pre><code>{`"integrates_with": {
  "tanstack-crud": {
    "slot": "route.beforeLoad",
    "inject": "templates/auth-guard-slot.hbs"
  }
}`}</code></pre>
      <p>
        When both packages are installed, tsx automatically threads the slot injection through the
        generator pipeline — no manual wiring required.
      </p>

      <h2>Next steps</h2>
      <ul>
        <li><a href="/docs/fpf/manifest">Full manifest field reference</a></li>
        <li><a href="/docs/fpf/publishing">End-to-end publishing guide</a></li>
        <li><a href="/docs/cli/framework">tsx framework commands</a></li>
      </ul>
    </>
  )
}
